"""initial schema

Revision ID: 1b1829952249
Revises: 
Create Date: 2026-07-11 06:03:37.458723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1829952249'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email')),
    sa.UniqueConstraint('google_sub', name=op.f('uq__users__google_sub'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__profiles__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__profiles')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq__profiles__user_id__name'))
    )
    op.create_index(op.f('ix__profiles__user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__sessions__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq__sessions__token_hash'))
    )
    op.create_index(op.f('ix__sessions__user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk__categories__parent_id__categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk__categories__profile_id__profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categories')),
    sa.UniqueConstraint('profile_id', 'category_name', name=op.f('uq__categories__profile_id__category_name'))
    )
    op.create_index(op.f('ix__categories__parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk__tags__profile_id__profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tags')),
    sa.UniqueConstraint('profile_id', 'name', name=op.f('uq__tags__profile_id__name'))
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('budget_limit', sa.Integer(), nullable=False),
    sa.Column('budget_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("budget_type IN ('weekly', 'monthly')", name=op.f('ck__budgets__budget_type')),
    sa.CheckConstraint('budget_limit  > 0', name=op.f('ck__budgets__budget_limit_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__budgets__category_id__categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk__budgets__profile_id__profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__budgets')),
    sa.UniqueConstraint('profile_id', 'category_id', 'budget_type', name=op.f('uq__budgets__profile_id__category_id__budget_type'))
    )
    op.create_table('recurring_transaction_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=25), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IS NULL OR frequency IN ('weekly', 'monthly')", name=op.f('ck__recurring_transaction_templates__frequency')),
    sa.CheckConstraint("transaction_type IN ('income', 'expense')", name=op.f('ck__recurring_transaction_templates__transaction_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck__recurring_transaction_templates__amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__recurring_transaction_templates__category_id__categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk__recurring_transaction_templates__profile_id__profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__recurring_transaction_templates'))
    )
    op.create_index(op.f('ix__recurring_transaction_templates__profile_id'), 'recurring_transaction_templates', ['profile_id'], unique=False)
    op.create_table('template_tags',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk__template_tags__tag_id__tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['recurring_transaction_templates.id'], name=op.f('fk__template_tags__template_id__recurring_transaction_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'tag_id', name=op.f('pk__template_tags'))
    )
    op.create_index(op.f('ix__template_tags__tag_id'), 'template_tags', ['tag_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('source_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('income', 'expense')", name=op.f('ck__transactions__transaction_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck__transactions__amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__transactions__category_id__categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk__transactions__profile_id__profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['recurring_transaction_templates.id'], name=op.f('fk__transactions__source_template_id__recurring_transaction_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__transactions'))
    )
    op.create_index(op.f('ix__transactions__profile_id__category_id__transaction_date'), 'transactions', ['profile_id', 'category_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix__transactions__profile_id__transaction_date'), 'transactions', ['profile_id', 'transaction_date'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk__transaction_tags__tag_id__tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk__transaction_tags__transaction_id__transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk__transaction_tags'))
    )
    op.create_index(op.f('ix__transaction_tags__tag_id'), 'transaction_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__transaction_tags__tag_id'), table_name='transaction_tags')
    op.drop_table('transaction_tags')
    op.drop_index(op.f('ix__transactions__profile_id__transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix__transactions__profile_id__category_id__transaction_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix__template_tags__tag_id'), table_name='template_tags')
    op.drop_table('template_tags')
    op.drop_index(op.f('ix__recurring_transaction_templates__profile_id'), table_name='recurring_transaction_templates')
    op.drop_table('recurring_transaction_templates')
    op.drop_table('budgets')
    op.drop_table('tags')
    op.drop_index(op.f('ix__categories__parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix__sessions__user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix__profiles__user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
