"""add type to categories and tags + make tag name a lower unique constraint

Revision ID: 6e779f224246
Revises: f011e068843c
Create Date: 2026-07-23 23:40:24.184304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e779f224246'
down_revision: Union[str, Sequence[str], None] = 'f011e068843c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- categories ----
    op.add_column('categories',
        sa.Column('type', sa.String(length=25), nullable=False, server_default='expense'))  # backfill
    op.alter_column('categories', 'type', server_default=None)                                # drop default
    op.create_check_constraint('ck__categories__type', 'categories', "type IN ('income', 'expense')")
    op.drop_index(op.f('uq__categories__profile_id__category_name_lower'), table_name='categories')
    op.create_index('uq__categories__profile_id__type__category_name_lower', 'categories',
        ['profile_id', 'type', sa.literal_column('lower(category_name)')], unique=True)


    # ---- tags ----
    op.add_column('tags',
        sa.Column('type', sa.String(length=25), nullable=False, server_default='expense'))
    op.alter_column('tags', 'type', server_default=None)
    op.create_check_constraint('ck__tags__type', 'tags', "type IN ('income', 'expense')")
    op.drop_constraint(op.f('uq__tags__profile_id__name'), 'tags', type_='unique')
    op.create_index('uq__tags__profile_id__type__name_lower', 'tags',
        ['profile_id', 'type', sa.literal_column('lower(name)')], unique=True)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ---- tags (reverse) ----
    op.drop_index('uq__tags__profile_id__type__name_lower', table_name='tags')
    op.drop_constraint('ck__tags__type', 'tags', type_='check')                    # added
    op.create_unique_constraint(op.f('uq__tags__profile_id__name'), 'tags', ['profile_id', 'name'])
    op.drop_column('tags', 'type')

    # ---- categories (reverse) ----
    op.drop_index('uq__categories__profile_id__type__category_name_lower', table_name='categories')
    op.drop_constraint('ck__categories__type', 'categories', type_='check')        # added
    op.create_index(op.f('uq__categories__profile_id__category_name_lower'), 'categories',
        ['profile_id', sa.literal_column('lower(category_name)')], unique=True)     # normalized (see note)
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
