"""Categories can be of same name for different parent

Revision ID: dac077754462
Revises: 8c20023c37bd
Create Date: 2026-08-02 06:32:33.684846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac077754462'
down_revision: Union[str, Sequence[str], None] = '8c20023c37bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq__categories__profile_id__type__category_name_lower'), table_name='categories')
    op.create_index('uq__categories__profile_id__type__parent_id__category_nameLower', 'categories', ['profile_id', 'type', 'parent_id', sa.literal_column('lower(category_name)')], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq__categories__profile_id__type__parent_id__category_nameLower', table_name='categories', postgresql_nulls_not_distinct=True)
    op.create_index(op.f('uq__categories__profile_id__type__category_name_lower'), 'categories', ['profile_id', 'type', sa.literal_column('lower(category_name::text)')], unique=True)
    # ### end Alembic commands ###
