"""make category names case insensitive

Revision ID: f011e068843c
Revises: 1b1829952249
Create Date: 2026-07-16 02:33:41.169863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f011e068843c'
down_revision: Union[str, Sequence[str], None] = '1b1829952249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__categories__profile_id__category_name'), 'categories', type_='unique')
    op.create_index('uq__categories__profile_id__category_name_lower', 'categories', ['profile_id', sa.literal_column('lower(category_name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq__categories__profile_id__category_name_lower', table_name='categories')
    op.create_unique_constraint(op.f('uq__categories__profile_id__category_name'), 'categories', ['profile_id', 'category_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
